---
name: Prepare new npm release

on:
  workflow_dispatch:
    inputs:
      npm-version-type:
        description: 'The npm version type we are publishing.'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  prepare:
    name: Prepare a new npm release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Run npm-prepare-release
        uses: Automattic/vip-actions/npm-prepare-release@v0.1.2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm-version-type: ${{ inputs.npm-version-type }}
