---
name: Publish to npm (if applicable)

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    if: contains( github.event.pull_request.labels.*.name, '[ Type ] NPM version update' ) && startsWith( github.head_ref, 'release/') && github.event.pull_request.merged == true

    steps:
      - uses: Automattic/vip-actions/npm-publish@v0.7.3
        with:
          USE_TRUSTED_PUBLISHING: 'true'
          PROVENANCE: 'false'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
